from enum import Enum


class qpsStatusType(Enum):
    """Status messages that can be sent to the backend."""

    DELIVERY_COMPLETE = "DELIVERY_COMPLETE"
    PICKUP_TIMEOUT = "PICKUP_TIMEOUT"
    MISSION_COMPLETE = "MISSION_COMPLETE"
    LOW_BATTERY = "LOW_BATTERY"
    LOW_BATTERY_ABORT = "LOW_BATTERY_ABORT"
    LOW_BATTERY_RETURN = "LOW_BATTERY_RETURN"
    LOW_BATTERY_CANNOT_RETURN = "LOW_BATTERY_CANNOT_RETURN"
    CRITICAL_BATTERY_RTL = "CRITICAL_BATTERY_RTL"
    CRITICAL_BATTERY_GROUNDED = "CRITICAL_BATTERY_GROUNDED"
    PRE_FLIGHT_FAILED = "PRE_FLIGHT_FAILED"
    ARM_FAILED = "ARM_FAILED"
    MARKER_NOT_FOUND = "MARKER_NOT_FOUND"
    FALLBACK_LAND = "FALLBACK_LAND"
